version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony_app
    volumes:
      - ./symfony:/var/www/symfony
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: mysql:8.0  # Remplace par `postgres:16` si tu utilises PostgreSQL
    container_name: symfony_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony_db
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: symfony_phpmyadmin
    restart: always
    ports:
      - "8081:80"  # On change le port externe
    environment:
      PMA_HOST: database
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - database


volumes:
  db_data:
